"use strict";

exports.__esModule = true;
var RECTANGLE_WIDTH = exports.RECTANGLE_WIDTH = 2;
var RECTANGLE_FIRST_ZOOM_WIDTH = exports.RECTANGLE_FIRST_ZOOM_WIDTH = 1;
var RECTANGLE_SECOND_ZOOM_WIDTH = exports.RECTANGLE_SECOND_ZOOM_WIDTH = 0.7;

var OVAL_WIDTH = exports.OVAL_WIDTH = 2;
var OVAL_FIRST_ZOOM_WIDTH = exports.OVAL_FIRST_ZOOM_WIDTH = 1;
var OVAL_SECOND_ZOOM_WIDTH = exports.OVAL_SECOND_ZOOM_WIDTH = 0.7;

var POINTS_WIDTH = exports.POINTS_WIDTH = 12;
var POINTS_FIRST_ZOOM_WIDTH = exports.POINTS_FIRST_ZOOM_WIDTH = 10;
var POINTS_SECOND_ZOOM_WIDTH = exports.POINTS_SECOND_ZOOM_WIDTH = 8;

var POLYGON_WIDTH = exports.POLYGON_WIDTH = 0.2;
var POLYGON_FIRST_ZOOM_WIDTH = exports.POLYGON_FIRST_ZOOM_WIDTH = 0.1;
var POLYGON_SECOND_ZOOM_WIDTH = exports.POLYGON_SECOND_ZOOM_WIDTH = 0.07;

var POLYGON_HIGHLIGHT_WIDTH = exports.POLYGON_HIGHLIGHT_WIDTH = 0.3;
var POLYGON_HIGHLIGHT_FIRST_ZOOM_WIDTH = exports.POLYGON_HIGHLIGHT_FIRST_ZOOM_WIDTH = 0.18;
var POLYGON_HIGHLIGHT_SECOND_ZOOM_WIDTH = exports.POLYGON_HIGHLIGHT_SECOND_ZOOM_WIDTH = 0.1;

var POLYGON_POINTS_WIDTH = exports.POLYGON_POINTS_WIDTH = 0.18;
var POLYGON_POINTS_FIRST_ZOOM_WIDTH = exports.POLYGON_POINTS_FIRST_ZOOM_WIDTH = 0.08;
var POLYGON_POINTS_SECOND_ZOOM_WIDTH = exports.POLYGON_POINTS_SECOND_ZOOM_WIDTH = 0.04;